/// Flutter icons MyFlutterApp
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
/// 
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Fontelico, Copyright (C) 2012 by Fontello project
///         Author:    Crowdsourced, for Fontello project
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://fontello.com
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class MyFlutterApp {
  MyFlutterApp._();

  static const _kFontFam = 'MyFlutterApp';
  static const String? _kFontPkg = null;

  static const IconData vector__2_ = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ac_unit = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData brightness_1 = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData signal = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bold = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData spin5 = IconData(0xe838, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hand_point_right = IconData(0xf0a4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData table = IconData(0xf0ce, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData compass = IconData(0xf14e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mail_squared = IconData(0xf199, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData paper_plane = IconData(0xf1d8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bomb = IconData(0xf1e2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hand_lizard = IconData(0xf258, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData snapchat_ghost = IconData(0xf2ac, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData snapchat_square = IconData(0xf2ad, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData meetup = IconData(0xf2e0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData adversal = IconData(0xf36a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData blogger_b = IconData(0xf37d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData buromobelexperte = IconData(0xf37f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dyalog = IconData(0xf399, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
